#
#Sun Apr 19 23:13:43 ECT 2026
codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.android.keystorePassword=
codename1.arg.android.xapplication_attr=android\:usesCleartextTraffic\="true"
codename1.arg.hyp.beamId=0219d8e1-f94a-4dfc-a3c6-86d6735676e4
codename1.arg.ios.newStorageLocation=true
codename1.arg.java.version=8
codename1.arg.maven.codenameone-core.version=7.0.229
codename1.arg.maven.codenameone-maven-plugin=7.0.229
codename1.cssTheme=true
codename1.displayName=CMConUniJavaGR5
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.ec.edu.monster
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.mainName=CMConUniJavaGR5
codename1.packageName=ec.edu.monster
codename1.secondaryTitle=Hello World
codename1.vendor=CodenameOne
codename1.version=1.0
